# Site settings
url: https://www.codeship.io/documentation
baseurl: /documentation
permalink: /:categories/:title/
tags_dir: tags
ubuntu_version: trusty

# Defaults for posts
defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: posts
    values:
      layout: page
      weight: 50

# Jekyll
exclude:
  - Readme.md
  - Guardfile
  - Gemfile
  - Gemfile.lock
gems:
  - octopress-autoprefixer
collections:
  faq:
    permalink: /faq/:path/
    output: true

# SASS
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  use_coderay: true
  coderay:
    coderay_line_numbers:      table
    coderay_css:               class

# Prose.io
prose:
  rooturl: '_posts'
  siteurl: 'https://codeship.io/documentation/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'page'
      - name: 'title'
        field:
          element: 'text'
          label: 'Page Title'
      - name: 'categories'
        field:
          type: 'select'
          label: 'Category'
          options:
            - name: 'Project Administration'
              value: 'administration'
            - name: 'Analytics'
              value: 'analytics'
            - name: 'Continuous Deployment'
              value: 'continuous-deployment'
            - name: 'Continuous Integration'
              value: 'continuous-integration'
            - name: 'Databases'
              value: 'databases'
            - name: 'FAQ'
              value: 'faq'
            - name: Integrations'
              value: 'integrations'
            - name: 'Languages & Services'
              value: 'languages'
            - name: 'Queues'
              value: queues
            - name: 'Security & Privacy'
              value: security
            - name: 'Services'
              value: services
            - name: 'Tutorials'
              value: tutorials
      - name: 'tags'
        field:
            element: 'multiselect'
            label: 'Tags'
            alterable: true
            options:
